In [50]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [51]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-75,  38,  71,  46,  61,  33])

In [52]:
tensor_ds = torch.tensor([[0.1,0.2,2], [2,3,2], [4.9,3, 5.2]])
tensor_ds

tensor([[0.1000, 0.2000, 2.0000],
        [2.0000, 3.0000, 2.0000],
        [4.9000, 3.0000, 5.2000]])

In [53]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [54]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [55]:
input = torch.empty(2,3)
input

tensor([[1.0000e-10, 1.0000e-05, 1.0000e+00],
        [1.0000e+05, 1.0000e+10, 0.0000e+00]])

In [56]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [57]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [58]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [59]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [60]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[4575657222473777152, 4575657222473777152, 4575657222473777152],
        [4575657222473777152, 4575657222473777152, 4575657222473777152]])

In [61]:
# GPU Processing

start_time = time.time()

zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0000000000


In [64]:
%%time   # How much time it takes to execute a block
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2) # Mul matrix
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.08780074
0.32111025
CPU times: total: 3.28 s
Wall time: 10.3 s


In [70]:
# Prob. Dist.
probabilities = torch.tensor([0.1, 0.9]) # 10% chance get 0 and 90% chance get 1
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [72]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [73]:
# Lower Triangle
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [76]:
# Upper Triangle
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [77]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [78]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [84]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2) # swap zeroth to twos position
out.shape

torch.Size([4, 3, 2])

In [87]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 8])

# Stack tensor in a new dimension Result 2D Matrix
stacked = torch.stack([tensor1, tensor2, tensor3])
stacked

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 8]])

In [89]:
# a simple neural network operation here nn is neural network
# X is input and y is output
# then (wi * xi + bias = y)

import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False) # A linear layer (nn.Linear) is initialized with input size 3 and output size 3
print(linear(sample)) # Apply linear transformation

tensor([-0.3411, -8.1059,  6.7075], grad_fn=<SqueezeBackward4>)


In [92]:
import torch.nn.functional as F

sample = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax function
softmax_output = F.softmax(sample, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [94]:
# init a embedding layer use for code words/char in a vector each vector represent a word 
# use for semantic relationships between words based on their context in a corpus

# Define the vocabulary size and embedding dimensions
vocab_size = 10000  # Number of unique words or characters in the vocabulary
embedding_dim = 100  # The dimension of each word's or character's embedding vector

# Create an Embedding layer
embedding = nn.Embedding(vocab_size, embedding_dim)

# Input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply embedding layer
output = embedding(input_indices)
output

tensor([[-0.0568, -0.3937, -0.1040,  1.3729, -0.8653,  0.0201,  0.5584,  1.4915,
          0.2536, -0.0843,  0.8097, -0.5479, -2.1831, -1.1142, -0.7753, -1.1672,
         -0.5340,  1.2971,  0.4993, -0.3103, -0.5322, -0.5331,  0.2120,  0.9571,
         -1.2293,  1.2482, -1.3824,  0.4866,  1.5308,  0.6216, -0.0806, -0.2970,
          0.4690,  0.4203, -0.5952,  0.9748, -0.9048,  0.2888,  1.6697,  0.8234,
         -0.0300,  0.2472, -0.0619, -0.8756, -0.5755, -0.0420, -0.7745,  0.2899,
         -0.3174, -0.0972,  0.1267, -0.4607, -1.5788, -1.2451, -0.9752,  0.2186,
         -0.3348,  0.5167, -0.1306, -1.5425,  1.0280,  0.5724,  0.7064,  0.6371,
          1.9467, -0.6457,  0.8569,  1.9493, -0.7670,  0.9770,  1.8694, -0.7362,
          0.9605, -0.0134,  0.1968,  0.3802, -1.0918, -1.2879, -1.4930,  0.4538,
          0.6627,  0.8338,  0.5065, -1.0885,  0.3996,  0.8297, -1.4113,  0.7289,
         -0.4543,  0.3679,  1.1621,  0.2015, -1.7052,  0.8421, -0.8082, -1.3370,
         -0.3578, -1.0553,  